<?php include "header.phtml"; ?>

<div id="main" class="nopadding">

    <div class="box">
        <div class="box-content nopadding">
            <div class="container-fluid">
                <div class="page-header">
                    <div class="pull-left">
                        <h1>Usuários</h1>
                    </div>

                </div>
                <div class="breadcrumbs">
                    <ul>
                        <li>
                            <a href="more-login.html">Configuração</a>
                            <i class="icon-angle-right"></i>
                        </li>
                        <li>
                            <a href="forms-basic.html">Usuários</a>
                            <i class="icon-angle-right"></i>
                        </li>
                    </ul>
                    <div class="close-bread">
                        <a href="#"><i class="icon-remove"></i></a>
                    </div>
                </div>

                <div class="box">
                    <div class="box-title nopadding">

                    </div>
                    <div class="box-content nopadding">
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="box box-color box-bordered">
                                    <div class="box-title" style="margin-bottom: -10px">
                                        <h3>
                                            <i class="icon-user"></i>
                                            Listagem de Usuários
                                        </h3>

                                        <div class="control-group pull-right" style="margin: 0; padding: 0; margin-right: 15px">
                                            <div class="controls">
                                                <div class="input-prepend">
                                                    <input class="span10" id="inputIcon" type="text" placeholder="Buscar...">
                                                    <span class="add-on"><i class="icon-search"></i></span>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="box-content nopadding">
                                        <table class="table table-hover table-nomargin">
                                            <thead>
                                            <tr>
                                                <th>Rendering engine</th>
                                                <th>Browser</th>
                                                <th class='hidden-350'>Platform(s)</th>
                                                <th class='hidden-1024'>Engine version</th>
                                                <th class='hidden-480'>CSS grade</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td>Trident</td>
                                                <td>
                                                    Internet
                                                    Explorer 4.0
                                                </td>
                                                <td class='hidden-350'>Win 95+</td>
                                                <td class='hidden-1024'>4</td>
                                                <td class='hidden-480'>X</td>
                                            </tr>
                                            <tr>
                                                <td>Presto</td>
                                                <td>Nokia N800</td>
                                                <td class='hidden-350'>N800</td>
                                                <td class='hidden-1024'>-</td>
                                                <td class='hidden-480'>A</td>
                                            </tr>
                                            <tr>
                                                <td>Misc</td>
                                                <td>NetFront 3.4</td>
                                                <td class='hidden-350'>Embedded devices</td>
                                                <td class='hidden-1024'>-</td>
                                                <td class='hidden-480'>A</td>
                                            </tr>
                                            <tr>
                                                <td>Misc</td>
                                                <td>Dillo 0.8</td>
                                                <td class='hidden-350'>Embedded devices</td>
                                                <td class='hidden-1024'>-</td>
                                                <td class='hidden-480'>X</td>
                                            </tr>
                                            <tr>
                                                <td>Misc</td>
                                                <td>Links</td>
                                                <td class='hidden-350'>Text only</td>
                                                <td class='hidden-1024'>-</td>
                                                <td class='hidden-480'>X</td>
                                            </tr>
                                            <tr>
                                                <td>Misc</td>
                                                <td>Lynx</td>
                                                <td class='hidden-350'>Text only</td>
                                                <td class='hidden-1024'>-</td>
                                                <td class='hidden-480'>X</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="table-pagination">
                                            <a href="#" class='disabled'>First</a>
                                            <a href="#" class='disabled'>Previous</a>
									<span>
										<a href="#" class='active'>1</a>
										<a href="#">2</a>
										<a href="#">3</a>
									</span>
                                            <a href="#">Next</a>
                                            <a href="#">Last</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

</div></div>

<?php include "footer.phtml"; ?>