<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Apple devices fullscreen -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <!-- Apple devices fullscreen -->
    <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <title>FLAT - Form Validation</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- Bootstrap responsive -->
    <link rel="stylesheet" href="css/bootstrap-responsive.min.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery.ui.theme.css">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Color CSS -->
    <link rel="stylesheet" href="css/themes.css">


    <!-- jQuery -->
    <script src="js/jquery.min.js"></script>

    <!-- Nice Scroll -->
    <script src="js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- imagesLoaded -->
    <script src="js/plugins/imagesLoaded/jquery.imagesloaded.min.js"></script>
    <!-- jQuery UI -->
    <script src="js/plugins/jquery-ui/jquery.ui.core.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.sortable.min.js"></script>
    <!-- slimScroll -->
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Bootbox -->
    <script src="js/plugins/bootbox/jquery.bootbox.js"></script>
    <!-- Bootbox -->
    <script src="js/plugins/form/jquery.form.min.js"></script>
    <!-- Validation -->
    <script src="js/plugins/validation/jquery.validate.min.js"></script>
    <script src="js/plugins/validation/additional-methods.min.js"></script>

    <!-- Theme framework -->
    <script src="js/eakroko.min.js"></script>
    <!-- Theme scripts -->
    <script src="js/application.min.js"></script>
    <!-- Just for demonstration -->
    <script src="js/demonstration.min.js"></script>

    <!--[if lte IE 9]>
    <script src="js/plugins/placeholder/jquery.placeholder.min.js"></script>
    <script>
        $(document).ready(function() {
            $('input, textarea').placeholder();
        });
    </script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <!-- Apple devices Homescreen icon -->
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png" />

</head>

<body>
<div id="navigation">
    <div class="container-fluid">
        <a href="#" id="brand">Adm-carenet</a>
        <a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title="Toggle navigation"><i class="icon-reorder"></i></a>
        <ul class='main-nav'>
            <li>
                <a href="index.html">
                    <span>Inicío</span>
                </a>
            </li>
            <li class='active'>
                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>
                    <i class="icon-cog"></i>
                    <span>Configurações</span>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu nopadding">
                    <li>
                        <a href="forms-basic.html"><i class="icon-user"> </i>Usuários</a>
                    </li>

                </ul>
            </li>

        </ul>
        <div class="user">
            <ul class="icon-nav">

                <li class='dropdown colo'>
                    <a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-tint"></i></a>
                    <ul class="dropdown-menu pull-right theme-colors">
                        <li class="subtitle">
                            Predefined colors
                        </li>
                        <li>
                            <span class='red'></span>
                            <span class='orange'></span>
                            <span class='green'></span>
                            <span class="brown"></span>
                            <span class="blue"></span>
                            <span class='lime'></span>
                            <span class="teal"></span>
                            <span class="purple"></span>
                            <span class="pink"></span>
                            <span class="magenta"></span>
                            <span class="grey"></span>
                            <span class="darkblue"></span>
                            <span class="lightred"></span>
                            <span class="lightgrey"></span>
                            <span class="satblue"></span>
                            <span class="satgreen"></span>
                        </li>
                    </ul>
                </li>

            </ul>
            <div class="dropdown">
                <a href="#" class='dropdown-toggle' data-toggle="dropdown">Vitor Mori <img src="img/demo/vitorMori.jpg" width="24" alt=""></a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="#">Configurar Conta</a>
                    </li>
                    <li>
                        <a href="more-login.html">Sair</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid" id="content">
    <div id="left">
        <div class="subnav">
            <div class="subnav-title">
                <a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span>Administração</span></a>
            </div>
            <ul class="subnav-menu nopadding">
                <li class='dropdown'>
                    <a href="#" data-toggle="dropdown">Configuração</a>
                    <ul class="dropdown-menu nopadding">
                        <li>
                            <a href="#">Usuários</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>

    </div>
    <div id="main" class="nopadding">

        <div class="box">
            <div class="box-content nopadding">
                <div class="container-fluid">
                    <div class="page-header">
                        <div class="pull-left">
                            <h1>Usuários</h1>
                        </div>

                    </div>
                    <div class="breadcrumbs">
                        <ul>
                            <li>
                                <a href="more-login.html">Configuração</a>
                                <i class="icon-angle-right"></i>
                            </li>
                            <li>
                                <a href="forms-basic.html">Usuários</a>
                                <i class="icon-angle-right"></i>
                            </li>
                        </ul>
                        <div class="close-bread">
                            <a href="#"><i class="icon-remove"></i></a>
                        </div>
                    </div>

                    <div class="box">
                        <div class="box-title nopadding">

                        </div>
                        <div class="box-content nopadding">
                            <div class="row-fluid">
                                <div class="span12">
                                    <div class="box box-color box-bordered">
                                        <div class="box-title" style="margin-bottom: -10px">
                                            <h3>
                                                <i class="icon-user"></i>
                                                Listagem de Usuários
                                            </h3>

                                            <div class="control-group pull-right" style="margin: 0; padding: 0; margin-right: 15px">
                                                <div class="controls">
                                                    <div class="input-prepend">
                                                        <input class="span10" id="inputIcon" type="text" placeholder="Buscar...">
                                                        <span class="add-on"><i class="icon-search"></i></span>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="box-content nopadding">
                                            <table class="table table-hover table-nomargin">
                                                <thead>
                                                <tr>
                                                    <th>Rendering engine</th>
                                                    <th>Browser</th>
                                                    <th class='hidden-350'>Platform(s)</th>
                                                    <th class='hidden-1024'>Engine version</th>
                                                    <th class='hidden-480'>CSS grade</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td>Trident</td>
                                                    <td>
                                                        Internet
                                                        Explorer 4.0
                                                    </td>
                                                    <td class='hidden-350'>Win 95+</td>
                                                    <td class='hidden-1024'>4</td>
                                                    <td class='hidden-480'>X</td>
                                                </tr>
                                                <tr>
                                                    <td>Presto</td>
                                                    <td>Nokia N800</td>
                                                    <td class='hidden-350'>N800</td>
                                                    <td class='hidden-1024'>-</td>
                                                    <td class='hidden-480'>A</td>
                                                </tr>
                                                <tr>
                                                    <td>Misc</td>
                                                    <td>NetFront 3.4</td>
                                                    <td class='hidden-350'>Embedded devices</td>
                                                    <td class='hidden-1024'>-</td>
                                                    <td class='hidden-480'>A</td>
                                                </tr>
                                                <tr>
                                                    <td>Misc</td>
                                                    <td>Dillo 0.8</td>
                                                    <td class='hidden-350'>Embedded devices</td>
                                                    <td class='hidden-1024'>-</td>
                                                    <td class='hidden-480'>X</td>
                                                </tr>
                                                <tr>
                                                    <td>Misc</td>
                                                    <td>Links</td>
                                                    <td class='hidden-350'>Text only</td>
                                                    <td class='hidden-1024'>-</td>
                                                    <td class='hidden-480'>X</td>
                                                </tr>
                                                <tr>
                                                    <td>Misc</td>
                                                    <td>Lynx</td>
                                                    <td class='hidden-350'>Text only</td>
                                                    <td class='hidden-1024'>-</td>
                                                    <td class='hidden-480'>X</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <div class="table-pagination">
                                                <a href="#" class='disabled'>First</a>
                                                <a href="#" class='disabled'>Previous</a>
									<span>
										<a href="#" class='active'>1</a>
										<a href="#">2</a>
										<a href="#">3</a>
									</span>
                                                <a href="#">Next</a>
                                                <a href="#">Last</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div></div>

</body>

</html>
